# Generated by Django 4.2 on 2023-05-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_created_date_alter_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='Autor',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='Comentário',
        ),
    ]
